font_family family="JetBrainsMono Nerd Font Mono"


# BEGIN_KITTY_THEME
# Box
include current-theme.conf
# END_KITTY_THEME
scrollback_lines 5000
cursor_trail 3
# select text with the keyboard (like vim)
map ctrl+s>[ launch --type=overlay --env PATH="$HOME/.local/bin:$PATH" --stdin-source=@screen_scrollback nvim -c 'set readonly noma nomodifiable buftype=nofile bufhidden=wipe nornu nonumber signcolumn=no' -c 'nnoremap q :q!<CR>' -c 'normal! G' -c "call search('^\s*\\S', 'b')" -
map ctrl+s>ctrl+[ launch --type=overlay --env PATH="$HOME/.local/bin:$PATH" --stdin-source=@screen_scrollback nvim -c 'set readonly noma nomodifiable buftype=nofile bufhidden=wipe nornu nonumber signcolumn=no' -c 'nnoremap q :q!<CR>' -c 'normal! G' -c "call search('^\s*\\S', 'b')" -
map ctrl+s>Escape launch --type=overlay --env PATH="$HOME/.local/bin:$PATH" --stdin-source=@screen_scrollback nvim -c 'set readonly noma nomodifiable buftype=nofile bufhidden=wipe nornu nonumber signcolumn=no' -c 'nnoremap q :q!<CR>' -c 'normal! G' -c "call search('^\s*\\S', 'b')" -
map ctrl+s>] paste_from_clipboard
map ctrl+s>ctrl+] paste_from_clipboard
